application: quizzically-app

version: 1

runtime: python27

api_version: 1
threadsafe: false


handlers:

- url: /images
  static_dir: images


- url: /

  script: main.py


  login: optional
- url: /deleteentry
  script: main.py


  login: admin
- url: /getvalue
  script: main.py



  login: optional
- url: /storeavalue
  script: main.py



  login: optional
- url: /sendemail
  script: main.py


libraries:
- name: PIL
  version: "1.1.7"
  
- name: webob
  version: "1.1.1"
  
- name: django
  version: "1.2"