INSERT INTO D_CATEGORY VALUES (20000, 'SPORT');
INSERT INTO D_CATEGORY VALUES (20001, 'GEOGRAPHY');
INSERT INTO D_CATEGORY VALUES (20002, 'ART & LITERATURE');
INSERT INTO D_CATEGORY VALUES (20003, 'ENTERTAINMENT');
INSERT INTO D_CATEGORY VALUES (20004, 'HISTORY');
INSERT INTO D_CATEGORY VALUES (20005, 'SCIENCE & NATURE');
INSERT INTO D_CATEGORY VALUES (20006, 'FOOD & DRINK');
INSERT INTO D_CATEGORY VALUES (20007, 'PEOPLE');