CREATE TABLE B_QUESTION
(
	`QUESTION_ID` INT NOT NULL 
	,PRIMARY KEY (QUESTION_ID)
	,`CATEGORY_ID` INT NOT NULL 
	,`SUB_CATEGORY_ID` INT  NULL 
	,`DIFFICULTY_ID` INT NOT NULL 
	,`LOCATION_ID` INT  NULL 
	,`ERA_ID` INT  NULL 
	,`QUESTION` VARCHAR(1000) NOT NULL 
	,`CORRECT_ANSWER` VARCHAR(1000) NOT NULL 
	,`WRONG_ANSWER_1` VARCHAR(1000) NOT NULL 
	,`WRONG_ANSWER_2` VARCHAR(1000) NOT NULL 
	,`WRONG_ANSWER_3` VARCHAR(1000) NOT NULL 
	,`QUESTION_CREATED` DATETIME NOT NULL 
	,`CREATED_BY_USER` INT  NULL 
	,`CREATED_BY_CLIENT` INT  NULL 
)
ENGINE=INNODB;

CREATE TABLE D_LOCATION
(
	`LOCATION_ID` INT NOT NULL 
	,PRIMARY KEY (LOCATION_ID)
	,`LOCATION` VARCHAR(100) NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE D_ERA
(
	`ERA_ID` INT NOT NULL 
	,PRIMARY KEY (ERA_ID)
	,`ERA` VARCHAR(100) NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE A_USER
(
	`USER_ID` INT NOT NULL 
	,PRIMARY KEY (USER_ID)
	,`USER_EMAIL` VARCHAR(100) NOT NULL 
	,`USER_PASSWORD` VARCHAR(100) NOT NULL 
	,`GENDER` VARCHAR(1)  NULL 
	,`BIRTHDAY` DATETIME  NULL 
	,`LOCATION_ID` INT  NULL 
	,`USER_UPDATES` VARCHAR(1)  NULL 
	,`USER_CREATED` DATETIME NOT NULL 
	,`RESET` VARCHAR(100)  NULL
	,`EXPIRE` VARCHAR(100)  NULL
	,`QUIZ_PLAYED` INT NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE A_CLIENT
(
	`CLIENT_ID` INT NOT NULL 
	,PRIMARY KEY (CLIENT_ID)
	,`CLIENT_EMAIL` VARCHAR(100) NOT NULL 
	,`CLIENT_PASSWORD` VARCHAR(100) NOT NULL 
	,`NAME` VARCHAR(100)  NULL 
	,`LOCATION_ID` INT  NULL 
	,`CLIENT_UPDATES` VARCHAR(1)  NULL 
	,`CLIENT_CREATED` DATETIME NOT NULL 
	,`QUIZ_CREDIT` INT NOT NULL 
	,`QUIZ_HOSTED` INT NOT NULL 
	,`RESET` VARCHAR(100)  NULL
	,`EXPIRE` VARCHAR(100)  NULL
)
ENGINE=INNODB;

CREATE TABLE B_QUIZ
(
	`QUIZ_ID` INT NOT NULL 
	,PRIMARY KEY (QUIZ_ID)
	,`QUIZ_CODE` VARCHAR(100) NOT NULL 
	,`NO_OF_QUESTIONS` INT NOT NULL 
	,`DIFFICULTY_ID` INT NOT NULL 
	,`LOCATION_ID` INT NOT NULL 
	,`QUIZ_REGISTERED` DATETIME NOT NULL 
	,`QUIZ_COMPLETED` DATETIME NOT NULL 
	,`NO_OF_USERS` INT NOT NULL 
	,`CLIENT_ID` INT NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE D_CATEGORY
(
	`CATEGORY_ID` INT NOT NULL 
	,PRIMARY KEY (CATEGORY_ID)
	,`CATEGORY` VARCHAR(100) NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE B_PARTICIPANT
(
	`PARTICIPANT_ID` INT NOT NULL 
	,PRIMARY KEY (PARTICIPANT_ID)
	,`USER_ID` INT NOT NULL 
	,`QUIZ_ID` INT NOT NULL 
	,`PARTICIPANT_CREATED` DATETIME NOT NULL 
	,`SCORE` INT NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE C_INTERACTION
(
	`INTERACTION_ID` INT NOT NULL 
	,PRIMARY KEY (INTERACTION_ID)
	,`PARTICIPANT_ID` INT NOT NULL 
	,`QUESTION_ID` INT NOT NULL 
	,`SELECTED_ANSWER` INT  NULL 
	,`CURRENT_SCORE` INT NOT NULL 
	,`INTERACTION_DATE` DATETIME NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE D_DIFFICULTY
(
	`DIFFICULTY_ID` INT NOT NULL 
	,PRIMARY KEY (DIFFICULTY_ID)
	,`DIFFICULTY` VARCHAR(100) NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE C_LOGIN
(
	`LOGIN_ID` INT NOT NULL 
	,PRIMARY KEY (LOGIN_ID)
	,`USER_ID` INT  NULL 
	,`CLIENT_ID` INT  NULL 
	,`LOGIN_DATE` DATETIME NOT NULL 
)
ENGINE=INNODB;

CREATE TABLE B_GAME
(
	`GAME_ID` INT NOT NULL 
	,PRIMARY KEY (GAME_ID)
	,`QUIZ_ID` INT NOT NULL 
	,`QUESTION_ID` INT  NULL 
	,`QUIZ_STATUS` VARCHAR(1) NOT NULL 
)
ENGINE=INNODB;

ALTER TABLE C_LOGIN ADD FOREIGN KEY (USER_ID) REFERENCES A_USER(USER_ID);

ALTER TABLE B_QUIZ ADD FOREIGN KEY (DIFFICULTY_ID) REFERENCES D_DIFFICULTY(DIFFICULTY_ID);

ALTER TABLE B_QUIZ ADD FOREIGN KEY (CLIENT_ID) REFERENCES A_CLIENT(CLIENT_ID);

ALTER TABLE B_QUESTION ADD FOREIGN KEY (CATEGORY_ID) REFERENCES D_CATEGORY(CATEGORY_ID);

ALTER TABLE B_QUESTION ADD FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES D_CATEGORY(CATEGORY_ID);

ALTER TABLE B_QUESTION ADD FOREIGN KEY (DIFFICULTY_ID) REFERENCES D_DIFFICULTY(DIFFICULTY_ID);

ALTER TABLE B_QUESTION ADD FOREIGN KEY (LOCATION_ID) REFERENCES D_LOCATION(LOCATION_ID);

ALTER TABLE B_QUESTION ADD FOREIGN KEY (ERA_ID) REFERENCES D_ERA(ERA_ID);

ALTER TABLE B_QUESTION ADD FOREIGN KEY (CREATED_BY_USER) REFERENCES A_USER(USER_ID);

ALTER TABLE B_QUESTION ADD FOREIGN KEY (CREATED_BY_CLIENT) REFERENCES A_CLIENT(CLIENT_ID);

ALTER TABLE B_PARTICIPANT ADD FOREIGN KEY (USER_ID) REFERENCES A_USER(USER_ID);

ALTER TABLE B_PARTICIPANT ADD FOREIGN KEY (QUIZ_ID) REFERENCES B_QUIZ(QUIZ_ID);

ALTER TABLE B_GAME ADD FOREIGN KEY (QUIZ_ID) REFERENCES B_QUIZ(QUIZ_ID);

ALTER TABLE B_GAME ADD FOREIGN KEY (QUESTION_ID) REFERENCES B_QUESTION(QUESTION_ID);

ALTER TABLE C_INTERACTION ADD FOREIGN KEY (PARTICIPANT_ID) REFERENCES B_PARTICIPANT(PARTICIPANT_ID);

ALTER TABLE C_INTERACTION ADD FOREIGN KEY (QUESTION_ID) REFERENCES B_QUESTION(QUESTION_ID);

ALTER TABLE B_QUIZ ADD FOREIGN KEY (LOCATION_ID) REFERENCES D_LOCATION(LOCATION_ID);

ALTER TABLE C_LOGIN ADD FOREIGN KEY (CLIENT_ID) REFERENCES A_CLIENT(CLIENT_ID);

ALTER TABLE A_USER ADD FOREIGN KEY (LOCATION_ID) REFERENCES D_LOCATION(LOCATION_ID);

ALTER TABLE A_CLIENT ADD FOREIGN KEY (LOCATION_ID) REFERENCES D_LOCATION(LOCATION_ID);